### ISSUE TITLE
Do not try to load empty fixture file  

### ISSUE THREAD

**Issue by dkondratovych** [seesawlabs/apitest#16]
Need to validate file length before loading fixture file, empty file causing an error

```
	testsuite_test.go:70: could not prepare database: could not load fixtures: could insert fixture from 'fixtures/project_business_assoc.yaml': Error 1054: Unknown column 'id' in 'field list'

```

**Comment by elgris** [comment]
This is something specific for some concrete team or project and is not related to API test itself. API test is not about databases, it's about testing API and generating documentation with absolutely no knowledge about surrounding infrastructure :)
